version: "3"

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/realstate
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=realstate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"